# -*- coding: utf-8 -*-
"""noise decrease_resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ynwbx4D9GrDa2F2k6exP5Cmg7WJHYP94
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms
from torchvision.models import resnet50
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm # For progress bars
import cv2 # For FFT/IFFT operations
import os
from torchvision.datasets import CIFAR10
from PIL import Image
import math

# Set a random seed for reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# --- Configuration ---
BATCH_SIZE = 128
NUM_EPOCHS = 50
LEARNING_RATE = 0.001
DATA_ROOT = './data'
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")
MAX_NOISE_STD_ABSOLUTE = 0.1 # Max std when noise_std_percentage is 1.0

class CIFAR10DegradationDataset(CIFAR10):
    def __init__(self, root, train=True, transform=None, download=False, cutoff_percentage=1.0, noise_std_percentage=0.0):
        super().__init__(root, train=train, transform=transform, download=download)
        self.cutoff_percentage = 1.0 # Fixed: No blur in this version
        self.max_noise_std_absolute = MAX_NOISE_STD_ABSOLUTE
        # noise_std_percentage: 1.0 = max noise, 0.0 = no noise
        self.set_noise_std_percentage(noise_std_percentage)


    def set_cutoff_percentage(self, pct: float):
        self.cutoff_percentage = 1.0 # Always ensure no blur

    def set_noise_std_percentage(self, pct: float):
        if not (0.0 <= pct <= 1.0):
            self.noise_std_percentage = max(0.0, min(1.0, pct))
        else:
            self.noise_std_percentage = pct

    def __getitem__(self, index):
        img_np = self.data[index]
        target = self.targets[index]
        img_float = np.float32(img_np) / 255.0
        img_processed_color = img_float

        # --- Apply Additive Gaussian Noise ---
        if self.noise_std_percentage > 0.0: # Only add if noise percentage is > 0
            current_noise_std = self.noise_std_percentage * self.max_noise_std_absolute
            noise = np.random.normal(0, current_noise_std, img_processed_color.shape).astype(np.float32)
            img_processed_color = img_processed_color + noise
            img_processed_color = np.clip(img_processed_color, 0.0, 1.0)

        img_pil = Image.fromarray(np.uint8(img_processed_color * 255.0))
        if self.transform is not None:
            img_pil = self.transform(img_pil)
        return img_pil, target

# --- Data Transforms ---
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

# --- Datasets & DataLoaders ---
print("Preparing datasets...")
# For Gaussian Noise Only Curriculum (DECREASING NOISE)
train_dataset_noise_only_curriculum = CIFAR10DegradationDataset(
    root=DATA_ROOT, train=True, download=True, transform=transform_train,
    cutoff_percentage=1.0,    # NO BLURRING
    noise_std_percentage=1.0  # Start with MAX noise
)
train_loader_noise_only_curriculum = DataLoader(
    train_dataset_noise_only_curriculum, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True if DEVICE.type == 'cuda' else False
)

# Standard CIFAR-10 for Baseline Training
train_dataset_baseline = datasets.CIFAR10(
    root=DATA_ROOT, train=True, download=True, transform=transform_train
)
train_loader_baseline = DataLoader(
    train_dataset_baseline, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True if DEVICE.type == 'cuda' else False
)

# Test Dataset
test_dataset = datasets.CIFAR10(
    root=DATA_ROOT, train=False, download=True, transform=transform_test
)
test_loader = DataLoader(
    test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True if DEVICE.type == 'cuda' else False
)
print("Datasets ready.")

# --- Training Function ---
def train_model(model, train_loader, test_loader, num_epochs, optimizer, criterion, scheduler=None,
                is_noise_curriculum=False, dataset_obj=None):
    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

    current_run_name = "Noise-Only Curriculum (Decreasing Noise)" if is_noise_curriculum else "Baseline"
    print(f"\n--- Starting Training: {current_run_name} ---")

    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0
        correct_train = 0
        total_train = 0

        if is_noise_curriculum and dataset_obj is not None:
            epochs_for_progression = max(1, num_epochs - 10) # Epochs over which curriculum changes
            # current_noise_pct will DECREASE from 1.0 to 0.0

            if epoch >= epochs_for_progression:
                current_noise_pct = 0.0 # Min noise (clear image) in the final stage
            else:
                progress = epoch / epochs_for_progression # progress goes from 0 to 1
                current_noise_pct = 1.0 - progress # Noise decreases from 1.0 down to 0.0

            dataset_obj.set_noise_std_percentage(current_noise_pct)
            dataset_obj.set_cutoff_percentage(1.0) # Ensure no blur

            print(f"Epoch {epoch+1}/{num_epochs} ({current_run_name}) - Curriculum Update: "
                  f"NoisePct={current_noise_pct:.3f} " # NP closer to 0 means clearer
                  f"(AbsStd~{current_noise_pct*dataset_obj.max_noise_std_absolute:.3f})")

        for inputs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs} (Train)", leave=False):
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * inputs.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total_train += labels.size(0)
            correct_train += (predicted == labels).sum().item()

        epoch_train_loss = running_loss / total_train
        epoch_train_acc = correct_train / total_train
        history['train_loss'].append(epoch_train_loss)
        history['train_acc'].append(epoch_train_acc)

        model.eval()
        val_loss = 0.0
        correct_val = 0
        total_val = 0
        with torch.no_grad():
            for inputs, labels in tqdm(test_loader, desc=f"Epoch {epoch+1}/{num_epochs} (Val)", leave=False):
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                outputs = model(inputs)
                loss_val_batch = criterion(outputs, labels)
                val_loss += loss_val_batch.item() * inputs.size(0)
                _, predicted_val = torch.max(outputs.data, 1)
                total_val += labels.size(0)
                correct_val += (predicted_val == labels).sum().item()

        epoch_val_loss = val_loss / total_val
        epoch_val_acc = correct_val / total_val
        history['val_loss'].append(epoch_val_loss)
        history['val_acc'].append(epoch_val_acc)

        print(f"Epoch {epoch+1}/{num_epochs} ({current_run_name}) - "
              f"Train Loss: {epoch_train_loss:.4f} Acc: {epoch_train_acc:.4f} | "
              f"Val Loss: {epoch_val_loss:.4f} Acc: {epoch_val_acc:.4f}")

        if scheduler:
            scheduler.step()
    print(f"--- Training Complete: {current_run_name} ---")
    return history

# --- Visualization of Degraded Images (Noise-Only, DECREASING NOISE) ---
print("\n--- Visualizing Noise-Degraded Images (Decreasing Noise) ---")
def visualize_noise_degradations(dataset_obj_vis, vis_epochs_indices, num_images=4, total_epochs_for_sched=NUM_EPOCHS):
    original_transform = dataset_obj_vis.transform
    dataset_obj_vis.transform = None

    fig, axes = plt.subplots(len(vis_epochs_indices), num_images,
                             figsize=(num_images * 2.5, len(vis_epochs_indices) * 2.5))
    if len(vis_epochs_indices) == 1: axes = axes.reshape(1, -1)

    epochs_for_progression_vis = max(1, total_epochs_for_sched - 10)

    for i, epoch_idx_sim in enumerate(vis_epochs_indices):
        temp_noise_pct = 0.0 # Default to min noise
        if epoch_idx_sim >= epochs_for_progression_vis:
            temp_noise_pct = 0.0 # Min noise (clear)
        else:
            progress_vis = epoch_idx_sim / epochs_for_progression_vis if epochs_for_progression_vis > 0 else 1.0
            temp_noise_pct = 1.0 - progress_vis # Noise decreases from 1.0

        dataset_obj_vis.set_noise_std_percentage(temp_noise_pct)
        dataset_obj_vis.set_cutoff_percentage(1.0)

        raw_images_pil = []
        num_samples_to_fetch = min(num_images, len(dataset_obj_vis))
        indices_to_fetch = np.random.choice(len(dataset_obj_vis), num_samples_to_fetch, replace=False) if num_samples_to_fetch > 0 else []
        for k_idx in indices_to_fetch:
            img_pil, _ = dataset_obj_vis[k_idx]
            raw_images_pil.append(img_pil)

        for j in range(min(num_images, len(raw_images_pil))):
            img_pil = raw_images_pil[j]
            ax = axes[i, j]
            ax.imshow(img_pil)
            # NP closer to 0 means clearer image
            ax.set_title(f'E{epoch_idx_sim+1}\nNP={temp_noise_pct:.2f}', fontsize=8)
            ax.axis('off')
        for j_extra in range(len(raw_images_pil), num_images):
            if i < axes.shape[0] and j_extra < axes.shape[1]: axes[i, j_extra].axis('off')

    fig.suptitle("Image Samples: Decreasing Noise Curriculum Stages", fontsize=14)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()
    dataset_obj_vis.transform = original_transform

epochs_to_visualize_indices = [0, NUM_EPOCHS // 3, max(0, (NUM_EPOCHS - 10) - 1) , NUM_EPOCHS -1]
if NUM_EPOCHS <=10: epochs_to_visualize_indices = sorted(list(set([0, NUM_EPOCHS//2, NUM_EPOCHS-1])))
if not epochs_to_visualize_indices : epochs_to_visualize_indices = [0]

# Initialize visualization dataset to start with max noise for decreasing curriculum
vis_dataset_noise_only = CIFAR10DegradationDataset(root=DATA_ROOT, train=True, download=True, transform=None,
                                                 cutoff_percentage=1.0, noise_std_percentage=1.0)
visualize_noise_degradations(vis_dataset_noise_only, epochs_to_visualize_indices, num_images=4)

# --- Model Definition (ResNet-50) ---
def create_resnet50_model():
    model = resnet50(weights=None)
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, 10)
    return model.to(DEVICE)

criterion = nn.CrossEntropyLoss()

# --- Run Baseline Training ---
print("\n--- Training ResNet-18: Baseline ---")
model_baseline = create_resnet50_model()
optimizer_baseline = optim.Adam(model_baseline.parameters(), lr=LEARNING_RATE)
scheduler_baseline = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer_baseline, T_max=NUM_EPOCHS)
history_baseline = train_model(model_baseline, train_loader_baseline, test_loader,
                               NUM_EPOCHS, optimizer_baseline, criterion, scheduler_baseline,
                               is_noise_curriculum=False)

# --- Run Gaussian Noise Only Curriculum Training (DECREASING NOISE) ---
print("\n--- Training ResNet-18: Gaussian Noise Only Curriculum (Decreasing Noise) ---")
model_noise_only_curriculum = create_resnet50_model()
optimizer_noise_only_curriculum = optim.Adam(model_noise_only_curriculum.parameters(), lr=LEARNING_RATE)
scheduler_noise_only_curriculum = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer_noise_only_curriculum, T_max=NUM_EPOCHS)
train_dataset_noise_only_curriculum.transform = transform_train
history_noise_only_curriculum = train_model(model_noise_only_curriculum, train_loader_noise_only_curriculum, test_loader,
                                             NUM_EPOCHS, optimizer_noise_only_curriculum, criterion, scheduler_noise_only_curriculum,
                                             is_noise_curriculum=True, dataset_obj=train_dataset_noise_only_curriculum)

# --- Visualization of Results ---
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.plot(history_baseline['val_acc'], label='Baseline Val Acc', marker='o', linestyle='-', markersize=4, alpha=0.7)
plt.plot(history_noise_only_curriculum['val_acc'], label='Decreasing Noise Curr. Val Acc', marker='^', linestyle=':', markersize=4, alpha=0.7)
plt.title('Validation Accuracy (Top-1) over Epochs', fontsize=14)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.legend(fontsize=10)
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 2, 2)
plt.plot(history_baseline['val_loss'], label='Baseline Val Loss', marker='o', linestyle='-', markersize=4, alpha=0.7)
plt.plot(history_noise_only_curriculum['val_loss'], label='Decreasing Noise Curr. Val Loss', marker='^', linestyle=':', markersize=4, alpha=0.7)
plt.title('Validation Loss over Epochs', fontsize=14)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.legend(fontsize=10)
plt.grid(True, linestyle='--', alpha=0.7)

plt.suptitle('Model Performance: Baseline vs. Decreasing Noise Curriculum (ResNet-50)', fontsize=16, y=1.02)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()

# --- Simplified Visualization of Results ---
plt.figure(figsize=(12, 5))

# Validation Accuracy
plt.subplot(1, 2, 1)
plt.plot(history_baseline['val_acc'], label='Baseline Val Acc')
plt.plot(history_noise_only_curriculum['val_acc'], label='Decrease Noise Acc')
plt.title('Validation Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

# Validation Loss
plt.subplot(1, 2, 2)
plt.plot(history_baseline['val_loss'], label='Baseline Val Loss')
plt.plot(history_noise_only_curriculum['val_loss'], label='Decreasing Noise Val Loss')
plt.title('Validation Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()